apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: catalog
  namespace: retail
spec:
  replicas: 4
  selector:
    matchLabels: { app: catalog }
  strategy:
    canary:
      canaryService: catalog-canary
      stableService: catalog-stable
      trafficRouting:
        istio:
          virtualService: catalog-vs
          destinationRule: catalog-dr
      steps:
        - setWeight: 5
        - pause: { duration: 60 }
        - setWeight: 25
        - pause: { duration: 120 }
        - setWeight: 50
        - pause: { duration: 180 }
  template:
    metadata:
      labels: { app: catalog }
    spec:
      containers:
        - name: catalog
          image: asia-docker.pkg.dev/PROJECT/nusmart/repo/catalog:REPLACEME_SHA
          ports: [{ containerPort: 8080, name: http }]
          resources:
            requests: { cpu: "100m", memory: "256Mi" }
            limits:   { cpu: "400m",  memory: "512Mi" }
          readinessProbe:
            httpGet: { path: /readyz, port: http }
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /healthz, port: http }
            initialDelaySeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-stable
  namespace: retail
spec:
  selector: { app: catalog }
  ports: [{ name: http, port: 80, targetPort: 8080 }]
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-canary
  namespace: retail
spec:
  selector: { rollouts-pod-template-hash: canary }
  ports: [{ name: http, port: 80, targetPort: 8080 }]
