apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: notifications
  namespace: retail
spec:
  replicas: 4
  selector:
    matchLabels: { app: notifications }
  strategy:
    canary:
      canaryService: notifications-canary
      stableService: notifications-stable
      trafficRouting:
        istio:
          virtualService: notifications-vs
          destinationRule: notifications-dr
      steps:
        - setWeight: 5
        - pause: { duration: 60 }
        - setWeight: 25
        - pause: { duration: 120 }
        - setWeight: 50
        - pause: { duration: 180 }
  template:
    metadata:
      labels: { app: notifications }
    spec:
      containers:
        - name: notifications
          image: asia-docker.pkg.dev/PROJECT/nusmart/repo/notifications:REPLACEME_SHA
          ports: [{ containerPort: 8080, name: http }]
          resources:
            requests: { cpu: "50m", memory: "128Mi" }
            limits:   { cpu: "200m",  memory: "256Mi" }
          readinessProbe:
            httpGet: { path: /readyz, port: http }
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /healthz, port: http }
            initialDelaySeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: notifications-stable
  namespace: retail
spec:
  selector: { app: notifications }
  ports: [{ name: http, port: 80, targetPort: 8080 }]
---
apiVersion: v1
kind: Service
metadata:
  name: notifications-canary
  namespace: retail
spec:
  selector: { rollouts-pod-template-hash: canary }
  ports: [{ name: http, port: 80, targetPort: 8080 }]
